[target.thumbv7em-none-eabihf]

rustflags = [
    # ---------------- required ----------------
    "-C",
    "link-arg=-Tlink.x",

    # # ---------------- this example is not using the defmt crate, do this is commented out ----------------
    # # "-C",
    # # "link-arg=-Tdefmt.x",

    # # ---------------- unused ----------------
    # # `flip-link` moves stack at the end of flash
    # # "-C", "linker=flip-link",

    # ---------------- The STM32WB5MMG aligns to 0x8000000 ----------------
    # enabling `--nmagic` is needed for the build to use the MEMORY.x section defined by the stm32wb-hal crate
    # Without this, (as fo writing) the start of flash defaults to 0x10000, See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
    "-C",
    "link-arg=--nmagic",
]

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)
